/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class ImageToByteArray extends javax.swing.JFrame {

    /**
     * Creates new form ImageToByteArray
     */
    public ImageToByteArray() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Load Image");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.showDialog(this, "Convert File");
        File f = jfc.getSelectedFile();
                
        if (f != null) {
            try {
                BufferedReader fr = new BufferedReader(new FileReader(f));

                //First Line = P3
                if (!fr.readLine().equals("P1")) {
                    System.err.println("Bad file type. Not pbm file type.");
                    return;
                }
                
                //constains unuseful data;
                fr.readLine();
                
                //gets file dimensions
                String[] dimensions = fr.readLine().split(" ");
                int[] dims = {Integer.parseInt(dimensions[0]), Integer.parseInt(dimensions[1])};

                
                String next = "";                
                int[] b = new int[dims[0] * dims[1]];
                int cnt = 0;

                while ((next = fr.readLine()) != null) {
                    for(char c : next.toCharArray()) {
                        b[cnt++] =  (c == '1') ? 1 : 0;                    
                    }
                }
                
                fr.close();

                // SSD1306 compatible data storage to an improved data transmission
                // the display is composed of 128 cols and 8 pages of 8 bit each
                // and then the goal is to have 128 bytes that represent the 
                // 8 x 128 bits of data of the first page and so on.
                
                int v;
                StringBuilder sb = new StringBuilder();
                sb.append("const byte ").append(f.getName().replace('.', '_')).append("[] PROGMEM ={");
                
                for (int i = 0; i < dims[1]/8; i++) {
                    for (int j = 0; j < dims[0]; j++) {
                        v =     1 * b[0*dims[0] + i*(dims[0] * 8) + j] + 
                                2 * b[1*dims[0] + i*(dims[0] * 8) + j] + 
                                4 * b[2*dims[0] + i*(dims[0] * 8) + j] + 
                                8 * b[3*dims[0] + i*(dims[0] * 8) + j] + 
                               16 * b[4*dims[0] + i*(dims[0] * 8) + j] + 
                               32 * b[5*dims[0] + i*(dims[0] * 8) + j] + 
                               64 * b[6*dims[0] + i*(dims[0] * 8) + j] + 
                              128 * b[7*dims[0] + i*(dims[0] * 8) + j];                        
                        sb.append(String.format("0x%02X, ", v));
                    }
                    sb.append("\r\n");
                }
                
                sb.replace(sb.length()-4, sb.length(), "};");
                
                jTextArea1.setText(sb.toString());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ImageToByteArray.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ImageToByteArray.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageToByteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageToByteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageToByteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageToByteArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageToByteArray().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
